version: '3'

services:
  db:
    image: postgres:10.1-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:3-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/data'

  ipfs:
    image: ipfs/go-ipfs:release
    restart: unless-stopped
    volumes:
      - 'ipfsexport:/export'
      - 'ipfsdata:/data/ipfs'
    ports:
      - "4001:4001"
      - "4002:4002"
      - "5001:5001"
      - "8080:8080"

  pgweb:
    image: sosedoff/pgweb
    environment:
        - DATABASE_URL=postgres://postgres:postgres@db:5432?sslmode=disable
    links:
        - db
    ports:
        - "8081:8081"
    depends_on:
      - db
    restart: "on-failure:10"

  web:
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/code/app
      - SERVICE_TYPE=web
    env_file: 'app/app/.env'
    build: .
    image: 'web'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    stdin_open: true
    tty: true

  celery_worker:
    image: 'web'
    restart: unless-stopped
    env_file: 'app/app/.env'
    environment:
      - SERVICE_TYPE=worker
      - CELERY_APP=app
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
      - web
    command: ["/code/bin/celery/worker.bash"]

  celery_beat:
    image: web
    restart: unless-stopped
    env_file:
      - app/app/.env
    environment:
      - SERVICE_TYPE=beat
      - CELERY_APP=app
    volumes:
      - .:/code
    depends_on:
      - celery_worker
    command: ["/code/bin/celery/worker.bash"]

  celery_flower:
    image: web
    restart: unless-stopped
    env_file:
      - app/app/.env
    environment:
      - SERVICE_TYPE=flower
      - CELERY_APP=app
    volumes:
      - .:/code
    depends_on:
      - celery_worker
    ports:
      - "5555:5555"
    command: ["/code/bin/celery/worker.bash"]

  testrpc:
    image: trufflesuite/ganache-cli
    restart: unless-stopped
    ports:
      - "8545:8545"
    command: "-a 1 --seed 2"

volumes:
  pgdata:
  redisdata:
  ipfsdata:
  ipfsexport:
